ALTER TABLE games ADD COLUMN IF NOT EXISTS base_first_runner VARCHAR(128);
ALTER TABLE games ADD COLUMN IF NOT EXISTS base_second_runner VARCHAR(128);
ALTER TABLE games ADD COLUMN IF NOT EXISTS base_third_runner VARCHAR(128);
